apiVersion: 1

datasources:
  - name: InfluxDB-K6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    isDefault: true
    jsonData:
      timeInterval: "5s"
      httpMode: GET
    version: 1
    editable: true
